//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arsiv
    {
        public int ArsivID { get; set; }
        public int OperasyonID { get; set; }
        public string Barkod { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> EkipID { get; set; }
        public string Tip { get; set; }
        public Nullable<System.DateTime> Zaman { get; set; }
        public Nullable<bool> AnahtarKaybi { get; set; }
        public Nullable<bool> AracHasar { get; set; }
        public Nullable<bool> CamAcik { get; set; }
        public Nullable<bool> VitesKonum { get; set; }
        public Nullable<bool> ElfrenKonum { get; set; }
        public Nullable<bool> Diger { get; set; }
        public Nullable<bool> SorunYok { get; set; }
        public Nullable<bool> SorunDurum { get; set; }
    }
}
