//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ekipler
    {
        public int EkipID { get; set; }
        public string EkipAdi { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
