//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SifreGirisZamanaları
    {
        public int GirisID { get; set; }
        public Nullable<System.DateTime> GirisZamani { get; set; }
        public string ErisilenSayfa { get; set; }
    }
}
